# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: alpine/git:latest #python:3.9

pipelines:
  default:
    - step:
        name: Test
        script:
          - sudo apt-get install fasta3
          - /usr/bin/fasta36 -f -12 -g -2 app/alignments/created_test.fasta app/alignments/allergens_data_set.fasta > app/alignments/a_cdp.txt
#          - /bin/sh -c "chmod +x app/alignments/fasta-36.3.8h_linux64/bin/fasta36"
#          - /bin/sh -c "app/alignments/fasta-36.3.8h_linux64/bin/fasta36 -f -12 -g -2 app/alignments/created_test.fasta app/alignments/allergens_data_set.fasta > app/alignments/a_cdp.txt"
#        script:
          #- cd food-allergy-prediction
#          - pip install -r requirements.txt
#          - ./run.py #cambiar por un archivo de test
#           - chmod +x app/alignments/fasta-36.3.8d/bin/fasta36
    - step:
        name: Build
        script:
          #- cd food-allergy-prediction
          - git archive --format=tar.gz master -o food-allergy-prediction.tar.gz
        artifacts:
          - food-allergy-prediction.tar.gz

    - step:
        name: Deploy to production
        deployment: production
        caches:
          - pip
        script:
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: food-allergy-prediction.tar.gz